fix: auto deploy gh_action
Signed-off-by: binaryYuki <60097976+binaryYuki@users.noreply.github.com>

diff --git a/.github/workflows/autoci.yml b/.github/workflows/autoci.yml
--- a/.github/workflows/autoci.yml
+++ b/.github/workflows/autoci.yml
@@ -121,9 +121,23 @@ jobs:
     runs-on: ubuntu-latest
     needs: docker
     steps:
-      - name: Dokploy Deployment
-        uses: benbristow/dokploy-deploy-action@0.0.1
-        with:
-          auth_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
-          application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
-          dokploy_url: ${{ secrets.DOKPLOY_URL }}
+      - name: Deploy Application
+        env:
+          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
+          DOKPLOY_AUTH_TOKEN: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
+          DOKPLOY_APPLICATION_ID: ${{ secrets.DOKPLOY_APPLICATION_ID }}
+        run: |
+          response=$(curl -X 'POST' \
+            "$DOKPLOY_URL/api/application.redeploy" \
+            -H 'accept: application/json' \
+            -H 'Content-Type: application/json' \
+            -H "Authorization: Bearer $DOKPLOY_AUTH_TOKEN" \
+            -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
+            -w "%{http_code}" \
+            -o /dev/null \
+            -s)
+
+          if [ "$response" -ne 200 ]; then
+            echo "Deployment failed with status code: $response $response_body"
+            exit 1
+          fi
